PRINT 'Inserting Application.StateProvinces'
GO

DECLARE @CurrentDateTime datetime2(7) = '20130101'
DECLARE @EndOfTime datetime2(7) =  '99991231 23:59:59.9999999'

DECLARE @CountryIDUS INT
SELECT @CountryIDUS = CountryID FROM [Application].Countries WHERE CountryName = N'United States'

INSERT [Application].StateProvinces 
  (StateProvinceID, StateProvinceCode, StateProvinceName, CountryID, SalesTerritory, Border, LatestRecordedPopulation, LastEditedBy, ValidFrom, ValidTo) 
VALUES 
  (1, 'AL', 'Alabama', @CountryIDUS, 'Southeast', NULL, 4833722,  1,  @CurrentDateTime,  @EndOfTime)
, (2, 'AK', 'Alaska', @CountryIDUS, 'Far West', NULL, 735132,  1,  @CurrentDateTime,  @EndOfTime)
, (3, 'AZ', 'Arizona', @CountryIDUS, 'Southwest', NULL, 6626624,  1,  @CurrentDateTime,  @EndOfTime)
, (4, 'AR', 'Arkansas', @CountryIDUS, 'Southeast', NULL, 2959373,  1,  @CurrentDateTime,  @EndOfTime)
, (5, 'CA', 'California', @CountryIDUS, 'Far West', NULL, 38332521,  1,  @CurrentDateTime,  @EndOfTime)
, (6, 'CO', 'Colorado', @CountryIDUS, 'Rocky Mountain', NULL, 5268367,  1,  @CurrentDateTime,  @EndOfTime)
, (7, 'CT', 'Connecticut', @CountryIDUS, 'New England', NULL, 3596080,  1,  @CurrentDateTime,  @EndOfTime)
, (8, 'DE', 'Delaware', @CountryIDUS, 'Mideast', NULL, 925749,  1,  @CurrentDateTime,  @EndOfTime)
, (9, 'DC', 'District of Columbia', @CountryIDUS, 'Mideast', NULL, 658893,  1,  @CurrentDateTime,  @EndOfTime)
, (10, 'FL', 'Florida', @CountryIDUS, 'Southeast', NULL, 19552860,  1,  @CurrentDateTime,  @EndOfTime)
, (11, 'GA', 'Georgia', @CountryIDUS, 'Southeast', NULL, 9992167,  1,  @CurrentDateTime,  @EndOfTime)
, (12, 'HI', 'Hawaii', @CountryIDUS, 'Far West', NULL, 1404054,  1,  @CurrentDateTime,  @EndOfTime)
, (13, 'ID', 'Idaho', @CountryIDUS, 'Rocky Mountain', NULL, 1612136,  1,  @CurrentDateTime,  @EndOfTime)
, (14, 'IL', 'Illinois', @CountryIDUS, 'Great Lakes', NULL, 12882135,  1,  @CurrentDateTime,  @EndOfTime)
, (15, 'IN', 'Indiana', @CountryIDUS, 'Great Lakes', NULL, 6570902,  1,  @CurrentDateTime,  @EndOfTime)
, (16, 'IA', 'Iowa', @CountryIDUS, 'Plains', NULL, 3090416,  1,  @CurrentDateTime,  @EndOfTime)
, (17, 'KS', 'Kansas', @CountryIDUS, 'Plains', NULL, 2893957,  1,  @CurrentDateTime,  @EndOfTime)
, (18, 'KY', 'Kentucky', @CountryIDUS, 'Southeast', NULL, 4395295,  1,  @CurrentDateTime,  @EndOfTime)
, (19, 'LA', 'Louisiana', @CountryIDUS, 'Southeast', NULL, 4625470,  1,  @CurrentDateTime,  @EndOfTime)
, (20, 'ME', 'Maine', @CountryIDUS, 'New England', NULL, 1328302,  1,  @CurrentDateTime,  @EndOfTime)
, (21, 'MD', 'Maryland', @CountryIDUS, 'Mideast', NULL, 5928814,  1,  @CurrentDateTime,  @EndOfTime)
, (22, 'MA', 'Massachusetts[E]', @CountryIDUS, 'New England', NULL, 6692824,  1,  @CurrentDateTime,  @EndOfTime)
, (23, 'MI', 'Michigan', @CountryIDUS, 'Great Lakes', NULL, 9895622,  1,  @CurrentDateTime,  @EndOfTime)
, (24, 'MN', 'Minnesota', @CountryIDUS, 'Plains', NULL, 5420380,  1,  @CurrentDateTime,  @EndOfTime)
, (25, 'MS', 'Mississippi', @CountryIDUS, 'Southeast', NULL, 2991207,  1,  @CurrentDateTime,  @EndOfTime)
, (26, 'MO', 'Missouri', @CountryIDUS, 'Plains', NULL, 6021988,  1,  @CurrentDateTime,  @EndOfTime)
, (27, 'MT', 'Montana', @CountryIDUS, 'Rocky Mountain', NULL, 1015165,  1,  @CurrentDateTime,  @EndOfTime)
, (28, 'NE', 'Nebraska', @CountryIDUS, 'Plains', NULL, 1868516,  1,  @CurrentDateTime,  @EndOfTime)
, (29, 'NV', 'Nevada', @CountryIDUS, 'Far West', NULL, 2790136,  1,  @CurrentDateTime,  @EndOfTime)
, (30, 'NH', 'New Hampshire', @CountryIDUS, 'New England', NULL, 1323459,  1,  @CurrentDateTime,  @EndOfTime)
, (31, 'NJ', 'New Jersey', @CountryIDUS, 'Mideast', NULL, 8899339,  1,  @CurrentDateTime,  @EndOfTime)
, (32, 'NM', 'New Mexico', @CountryIDUS, 'Southwest', NULL, 2085287,  1,  @CurrentDateTime,  @EndOfTime)
, (33, 'NY', 'New York', @CountryIDUS, 'Mideast', NULL, 19651127,  1,  @CurrentDateTime,  @EndOfTime)
, (34, 'NC', 'North Carolina', @CountryIDUS, 'Southeast', NULL, 9848060,  1,  @CurrentDateTime,  @EndOfTime)
, (35, 'ND', 'North Dakota', @CountryIDUS, 'Plains', NULL, 723393,  1,  @CurrentDateTime,  @EndOfTime)
, (36, 'OH', 'Ohio', @CountryIDUS, 'Great Lakes', NULL, 11570808,  1,  @CurrentDateTime,  @EndOfTime)
, (37, 'OK', 'Oklahoma', @CountryIDUS, 'Southwest', NULL, 3850568,  1,  @CurrentDateTime,  @EndOfTime)
, (38, 'OR', 'Oregon', @CountryIDUS, 'Far West', NULL, 3930065,  1,  @CurrentDateTime,  @EndOfTime)
, (39, 'PA', 'Pennsylvania', @CountryIDUS, 'Mideast', NULL, 12773801,  1,  @CurrentDateTime,  @EndOfTime)
, (40, 'PR', 'Puerto Rico (US Territory)', @CountryIDUS, 'External', NULL, 3474182,  1,  @CurrentDateTime,  @EndOfTime)
, (41, 'RI', 'Rhode Island', @CountryIDUS, 'New England', NULL, 1051511,  1,  @CurrentDateTime,  @EndOfTime)
, (42, 'SC', 'South Carolina', @CountryIDUS, 'Southeast', NULL, 4774839,  1,  @CurrentDateTime,  @EndOfTime)
, (43, 'SD', 'South Dakota', @CountryIDUS, 'Plains', NULL, 844877,  1,  @CurrentDateTime,  @EndOfTime)
, (44, 'TN', 'Tennessee', @CountryIDUS, 'Southeast', NULL, 6495978,  1,  @CurrentDateTime,  @EndOfTime)
, (45, 'TX', 'Texas', @CountryIDUS, 'Southwest', NULL, 26448193,  1,  @CurrentDateTime,  @EndOfTime)
, (46, 'UT', 'Utah', @CountryIDUS, 'Rocky Mountain', NULL, 2900872,  1,  @CurrentDateTime,  @EndOfTime)
, (47, 'VT', 'Vermont', @CountryIDUS, 'New England', NULL, 626630,  1,  @CurrentDateTime,  @EndOfTime)
, (48, 'VI', 'Virgin Islands (US Territory)', @CountryIDUS, 'External', NULL, 104737,  1,  @CurrentDateTime,  @EndOfTime)
, (49, 'VA', 'Virginia', @CountryIDUS, 'Southeast', NULL, 8260405,  1,  @CurrentDateTime,  @EndOfTime)
, (50, 'WA', 'Washington', @CountryIDUS, 'Far West', NULL, 6971406,  1,  @CurrentDateTime,  @EndOfTime)
, (51, 'WV', 'West Virginia', @CountryIDUS, 'Southeast', NULL, 1854304,  1,  @CurrentDateTime,  @EndOfTime)
, (52, 'WI', 'Wisconsin', @CountryIDUS, 'Great Lakes', NULL, 5742713,  1,  @CurrentDateTime,  @EndOfTime)
, (53, 'WY', 'Wyoming', @CountryIDUS, 'Rocky Mountain', NULL, 582658,  1,  @CurrentDateTime,  @EndOfTime)
GO
